@api = http://localhost:4000/products

GET {{api}}

###
POST   {{api}}
Content-Type: application/json

{
	"id": 12
	
}

###
GET {{api}}/12

###
DELETE {{api}}/8

###

PUT {{api}}/8
Content-Type: application/json

{
	"name": "nose",
	"description": "cualquier cosaaaaa",
	"quantity": 400
} 